---
- name: Install and configure Zabbix agent on other hosts
  hosts: bastion, web-group, zabbix
  become: yes

  vars:
    zabbix_repo_url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu24.04_all.deb"
    zabbix_server_ip: "zabbix.ru-central1.internal"

  tasks:
    - name: Install Zabbix repository
      apt:
        deb: "{{ zabbix_repo_url }}"
      register: zabbix_repo_installed

    - name: Update apt cache
      apt:
        update_cache: yes
      when: zabbix_repo_installed.changed

    - name: Install Zabbix agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix agent to connect to Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"
      notify: Restart Zabbix agent

    - name: Start and enable Zabbix agent service
      service:
        name: zabbix-agent
        state: started
        enabled: true

  handlers:
    - name: Restart Zabbix agent
      service:
        name: zabbix-agent
        state: restarted
