---
- name: Setup user and deploy web pages with NGINX on Ubuntu
  hosts: web-1
  become: true

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Start and enable NGINX service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Create web page for web-1
      template:
        src: web1_template.html.j2
        dest: /var/www/html/index.html
      when: inventory_hostname == "web-1"
