---
- name: Установка Kibana
  hosts: kibana
  become: yes
  tasks:
    - name: Добавление репозитория Kibana
      shell: echo "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main" | tee /etc/apt/sources.list.d/elastic-8.x.list

    - name: Обновление индекса пакетов
      apt:
        update_cache: yes

    - name: Установка Kibana
      apt:
        name: kibana
        state: present

    - name: Включение и запуск Kibana
      systemd:
        name: kibana
        enabled: yes
        state: started

    - name: Настройка параметров в kibana.yml
      block:
        - name: Установка или изменение ключей в kibana.yml
          lineinfile:
            path: /etc/kibana/kibana.yml
            regexp: '^#?{{ item.key }}'
            line: "{{ item.key }}: {{ item.value }}"
            create: yes
          with_items:
            - { key: 'server.port', value: '5601' }
            - { key: 'server.host', value: '"0.0.0.0"' }
            - { key: 'elasticsearch.hosts', value: '["https://elasticsearch:9200"]' }
            - { key: 'elasticsearch.username', value: '"kibana_system"' }
            - { key: 'elasticsearch.password', value: '"6tcXENthAlB1s0zqacgj"' }
            - { key: 'elasticsearch.ssl.verificationMode', value: 'none' }

    - name: Перезапуск Kibana после изменений конфигурации
      systemd:
        name: kibana
        state: restarted
        enabled: yes
