---
- name: Установка Elasticsearch
  hosts: elasticsearch
  become: yes
  tasks:
    - name: Добавление репозитория Elastic
      shell: echo "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main" | tee /etc/apt/sources.list.d/elastic-8.x.list

    - name: Обновление индекса пакетов
      apt:
        update_cache: yes

    - name: Установка Elasticsearch
      apt:
        name: elasticsearch
        state: present

    - name: Включение и запуск Elasticsearch
      systemd:
        name: elasticsearch
        enabled: yes
        state: started

    - name: Настройка параметров в elasticsearch.yml
      block:
        - name: Установка или изменение ключей в elasticsearch.yml
          lineinfile:
            path: /etc/elasticsearch/elasticsearch.yml
            regexp: '^#?{{ item.key }}'
            line: "{{ item.key }}: {{ item.value }}"
            create: yes
          with_items:
            - { key: 'network.host', value: '0.0.0.0' }
            - { key: 'discovery.seed_hosts', value: '["127.0.0.1", "[::1]"]' }
            - { key: 'xpack.security.enabled', value: 'true' }
            - { key: 'xpack.security.enrollment.enabled', value: 'true' }
            - { key: 'xpack.security.http.ssl.enabled', value: 'true' }
            - { key: 'xpack.security.transport.ssl.enabled', value: 'true' }
            - { key: 'xpack.security.transport.ssl.verification_mode', value: 'certificate' }
            - { key: 'xpack.security.transport.ssl.keystore.path', value: 'certs/transport.p12' }
            - { key: 'xpack.security.transport.ssl.truststore.path', value: 'certs/transport.p12' }
            - { key: 'xpack.security.http.ssl.keystore.path', value: 'certs/http.p12' }
            - { key: 'cluster.initial_master_nodes', value: '["elasticsearch"]' }
            - { key: 'http.host', value: '0.0.0.0' }

    - name: Перезапуск Elasticsearch для применения конфигурации
      systemd:
        name: elasticsearch
        state: restarted

    - name: Сброс пароля для пользователя elastic
      shell: yes | /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic
      register: reset_password_result
      changed_when: true

    - name: Вывод сгенерированного пароля
      debug:
        msg: "Сгенерированный пароль для пользователя 'elastic': {{ reset_password_result.stdout }}"

    - name: Сброс пароля для пользователя kibana_system
      shell: yes | /usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana_system
      register: reset_password_result
      changed_when: true

    - name: Вывод сгенерированного пароля
      debug:
        msg: "Сгенерированный пароль для пользователя 'kibana_system': {{ reset_password_result.stdout }}"