---
- name: Установка Filebeat
  hosts: web-group
  become: yes
  tasks:
    - name: Добавление репозитория Filebeat
      shell: echo "deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/8/ stable main" | tee /etc/apt/sources.list.d/elastic-8.x.list

    - name: Обновление индекса пакетов
      apt:
        update_cache: yes

    - name: Установка Filebeat
      apt:
        name: filebeat
        state: present

    - name: Включение и запуск Filebeat
      systemd:
        name: filebeat
        enabled: yes
        state: started

    - name: Подключение модуля Nginx в Filebeat
      shell: filebeat modules enable nginx

    - name: Создание резервной копии filebeat.yml
      command: cp /etc/filebeat/filebeat.yml /etc/filebeat/filebeat.yml.old

    - name: Создание резервной копии nginx.yml
      command: cp /etc/filebeat/modules.d/nginx.yml /etc/filebeat/modules.d/nginx.yml.old

    - name: Копирование локального файла filebeat.yml на сервер
      copy:
        src: filebeat-files/filebeat.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Копирование локального файла nginx.yml на сервер
      copy:
        src: filebeat-files/nginx.yml
        dest: /etc/filebeat/modules.d/nginx.yml
      
    - name: Перезапуск filebeat после изменений конфигурации
      systemd:
        name: filebeat
        state: restarted
        enabled: yes
