---
- name: Установка Zabbix Agent'ов на хосты
  hosts: all
  become: yes

  vars:
    zabbix_repo_url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu24.04_all.deb"
    zabbix_server_ip: "zabbix.ru-central1.internal"

  tasks:
    - name: Установка репазитория Zabbix
      apt:
        deb: "{{ zabbix_repo_url }}"
      register: zabbix_repo_installed

    - name: Обновление apt
      apt:
        update_cache: yes
      when: zabbix_repo_installed.changed

    - name: Установка Zabbix agent
      apt:
        name: zabbix-agent
        state: present

    - name: Изменение конфигурации Zabbix агента
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ '172.18.0.3' if inventory_hostname == 'zabbix' else zabbix_server_ip }}"
      notify: Рестарт Zabbix agent

    - name: Запуск Zabbix agent сервиса
      service:
        name: zabbix-agent
        state: started
        enabled: true

  handlers:
    - name: Рестарт Zabbix agent
      service:
        name: zabbix-agent
        state: restarted
